### ISSUE TITLE
Error 1.19.3

### ISSUE THREAD

**Issue by Smudgge** [Seyarada/PandeLootPlus#6]
`PandeLootPlus` #73
`Minecraft` 1.19.3

**Error**
```
[19:58:15 ERROR]: Could not pass event MythicMobDeathEvent to PandeLoot v1.73
java.lang.NumberFormatException: For input string: "0.2"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Long.parseLong(Long.java:708) ~[?:?]
        at java.lang.Long.parseLong(Long.java:831) ~[?:?]
        at net.seyarada.pandeloot.utils.MathUtils$1.parseFactor(MathUtils.java:118) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.utils.MathUtils$1.parseTerm(MathUtils.java:99) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.utils.MathUtils$1.parseExpression(MathUtils.java:90) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.utils.MathUtils$1.parse(MathUtils.java:78) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.utils.MathUtils.eval(MathUtils.java:138) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.flags.conditions.ChanceFlag.onCheck(ChanceFlag.java:17) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.drops.IDrop.passesConditions(IDrop.java:45) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.drops.LootDrop.collectDrops(LootDrop.java:176) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.drops.LootDrop.build(LootDrop.java:83) ~[PandeLootPlus #73.jar:?]
        at net.seyarada.pandeloot.compatibility.mythicmobs.MythicMobsListener.onDeath(MythicMobsListener.java:61) ~[PandeLootPlus #73.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor654.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1907]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:647) ~[MythicMobs 5.2.1.jar:?]
        at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144) ~[MythicMobs 5.2.1.jar:?]
        at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131) ~[MythicMobs 5.2.1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1907]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:888) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1825) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1720) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1535) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1354) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2235) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2931) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2853) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[19:58:15 INFO]: Named entity EntityZombieHusk['Paparazzi [5/5]'/97828, uuid='88bdb405-ad82-4e8b-95ee-94e8e2a42119', l='ServerLevel[world]', x=3219.70, y=74.00, z=15749.01, cpos=[201, 984], tl=18, v=true] died: Paparazzi [5/5] was slain by Smudyy
```

**Comment by Smudgge** [comment]
This happens to every mob. We have had to disable all bosses in the mean time, let me know if there's something we can do on our end :3

**Comment by Superalex0102** [comment]
I also have this issue
