### ISSUE TITLE
1.20.1 Bug

### ISSUE THREAD

**Issue by Smudgge** [Seyarada/PandeLootPlus#8]
Version: 88

```
[16:24:31 ERROR]: Could not pass event MythicMobDeathEvent to PandeLoot v1.88
java.lang.IllegalAccessError: class net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1 tried to access private method 'void net.minecraft.world.entity.Display$TextDisplay.b(int)' (net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1 is in unnamed module of loader 'PandeLootPlus #88.jar' @1c2e0b8e; net.minecraft.world.entity.Display$TextDisplay is in unnamed module of loader java.net.URLClassLoader @46ee7fe8)
        at net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1.hologram(V1_20_R1.java:66) ~[PandeLootPlus #88.jar:?]
        at net.seyarada.pandeloot.drops.LootDrop.displayScoreHolograms(LootDrop.java:218) ~[PandeLootPlus #88.jar:?]
        at net.seyarada.pandeloot.compatibility.mythicmobs.MythicMobsListener.onDeath(MythicMobsListener.java:63) ~[PandeLootPlus #88.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1000.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2035]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:721) ~[MythicMobs 5.3.5.jar:?]
        at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144) ~[MythicMobs 5.3.5.jar:?]
        at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131) ~[MythicMobs 5.3.5.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2035]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:937) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1859) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1751) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1563) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2287) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3019) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2941) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2035]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        ```

**Comment by tyn7mau** [comment]
Are you using purpur?

**Comment by Smudgge** [comment]
Yes

**Comment by Surtryyds** [comment]
Could not pass event MythicMobDeathEvent to PandeLoot v1.88
java.lang.IllegalAccessError: class net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1 tried to access private method 'void net.minecraft.world.entity.Display$TextDisplay.b(int)' (net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1 is in unnamed module of loader 'PandeLootPlus-88.jar' @2bc84c0c; net.minecraft.world.entity.Display$TextDisplay is in unnamed module of loader java.net.URLClassLoader @1edf1c96)
        at net.seyarada.pandeloot.nms.v1_20_R1.V1_20_R1.hologram(V1_20_R1.java:66) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.flags.effects.HologramFlag.attachedHologram(HologramFlag.java:85) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.flags.effects.HologramFlag.onCallEntity(HologramFlag.java:67) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.flags.FlagPack.trigger(FlagPack.java:59) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.drops.ActiveDrop.<init>(ActiveDrop.java:69) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.drops.ItemDrop.lambda$run$0(ItemDrop.java:41) ~[PandeLootPlus-88.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItem(CraftWorld.java:707) ~[purpur-1.20.1.jar:git-Purpur-2062]        at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.dropItemNaturally(CraftWorld.java:727) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.seyarada.pandeloot.drops.ItemDrop.run(ItemDrop.java:37) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.drops.LootDrop.drop(LootDrop.java:164) ~[PandeLootPlus-88.jar:?]
        at net.seyarada.pandeloot.compatibility.mythicmobs.MythicMobsListener.onDeath(MythicMobsListener.java:66) ~[PandeLootPlus-88.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor921.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:721) ~[MythicMobs-5.3.5.jar:?]
        at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144) ~[MythicMobs-5.3.5.jar:?]
        at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131) ~[MythicMobs-5.3.5.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:937) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1863) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1755) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1567) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2302) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:3010) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2932) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by Surtryyds** [comment]
I'm having the same problem.
MythicMobs version 5.3.5-64893d49
PandeLoot version v1.88
